### ISSUE TITLE
can't export Excel2007+

### ISSUE THREAD

**Issue by alemedinam** [kartik-v/yii2-export#142] opened 2016-05-31 20:29 UTC
I can't export to Excel2007+. It has no PHP or Yii error but browser redirects to an error with "File not found" message.

``` php
    <?= \kartik\export\ExportMenu::widget([
            'dataProvider' => $dataProvider,
            'columns' => [
                ['class' => 'kartik\grid\SerialColumn'],
                'NombreUniversitarioEncode',
            ],
            'asDropdown' => false
    ?>
```

I have no error when export to Excel2003+

yii2-export 1.2.5
PHP Version 5.4.7
Linux Mint 17.2

**Comment by zlakomanoff** [comment] 2016-07-19 09:33
BUMP: the same issue

yii2-export: latest
PHP Version 7.0.8
Arch Linux

**Comment by kartik-v** [comment] 2016-08-03 16:09
Cannot reproduce this with PHP 5.x... you can [cross check this on the demos page](http://demos.krajee.com/export-demo-dtl/custom-menu-list).

Have not tested this on PHP v7... you may need to check if there is a PHPExcel dependency needed.

**Comment by Bhoft** [comment] 2017-05-09 10:08
I have a similar issue but only with the Excel 95+ export? (the .xls file)
the 2007+ (.xlsx file) is exported without any problems.

The strange thing is both exports are working with php 7.0.0
But doesn't work with php 7.1.0 or fresh installed 7.1.4.
So it must be have to do something with strict parameter handling.

i have:
phpoffice/phpexcel  1.8.x-dev 185bf41 so the latest version is installed.

It looks like that this is more of an issue of php excel.
If i disable the stream output (so a file is been generated) i get the some warning.

PHP Warning – yii\base\ErrorException
A non-numeric value encountered
vendor\phpoffice\phpexcel\Classes\PHPExcel\Cell.php  at line 843 

this issue is already known here but closed?
https://github.com/PHPOffice/PHPExcel/issues/1110

the export also works if i set the error level so that warnings are ignored.
error_reporting(E_ALL ^ E_WARNING );

Maybe it also has something to do with the content of the exported table. Because i can't understand why in your case the Excel 2007 export created problems. But of course they were changes both in yii2-export as well as in PHPExcel.

**Comment by Bhoft** [comment] 2017-05-09 12:57
I have get down to these lines which produces the error in my case.


in ExportMenu::generateBody

    //Set autofilter on
    $this->_objPHPExcelSheet->setAutoFilter(
       self::columnName(1) . $this->_beginRow . ":" . self::columnName($this->_endCol) . $this->_endRow
    );

If i comment out these lines the export of the xls file (Excel 95+) works without any further problems.

I also tested out several other things but it makes no difference how this is called.

    // manually test
    $this->_objPHPExcelSheet->setAutoFilter('A1:E10');
    // set by row and column
    $this->_objPHPExcelSheet->setAutoFilterByColumnAndRow($pColumn1 = 0, $pRow1 = 1, $pColumn2 = 0, $pRow2 = 1);

But it is some issue of PHPExcel which needs to be fixed.

**Comment by Bhoft** [comment] 2017-05-11 08:03
I have created an issue on the PhpExcel as linked above.

But their answer is "Migrate to PhpSpreadsheet for support of PHP 7.1".
So this issue won't be fixed in PHPExcel.

Maybe the switch should be done to use PhpSpreadsheet  instead of PhpExcel.
Or at least reduce the error_level to ignore warnings (which i guess produces many exporting errors).

**Comment by NestorAcevedo** [comment] 2018-01-11 17:55
Related to this issue: https://github.com/kartik-v/yii2-export/issues/182
I try in both formats getting the same result.

Tested on AWS.

Ironically in localhost works well.

**Comment by Eseperio** [comment] 2018-02-05 12:32
This is a bug in Phpexcel with Php 7. 
@neoacevedo Have you checked what is your php version on localhost?

**Comment by kartik-v** [comment] 2018-02-05 15:11
PHPExcel is now obsolete.

The extension now uses the new version of the above lib called `phpoffice\PhpSpreadsheet` with support for PHP 7.x. You may want to upgrade to latest version of yii2-export via composer.

**Closed** 2018-02-05 15:11 UTC
