### ISSUE TITLE
$dataProvider configuration wrong?

### ISSUE THREAD

**Issue by kevinkt** [kartik-v/yii2-export#105] opened 2016-01-04 07:30 UTC
```
<?Php

use yii\data\SqlDataProvider;

$provider = new SqlDataProvider([
    'sql' => "SELECT email,full_name FROM entries WHERE contest_id=$contest_id",
    'pagination' => [
        'pageSize' => 10,
    ],
    'sort' => [
        'attributes' => [
            'email',
        ],
    ],
]);
// returns an array of data rows
$dataProvider = $provider->getModels();

$gridColumns = [
    ['class' => 'yii\grid\SerialColumn'],
    'full_name',
    'email',
    ['class' => 'yii\grid\ActionColumn'],
];
 
// Renders a export dropdown menu
echo ExportMenu::widget([
    'dataProvider' => $dataProvider,
    'columns' => $gridColumns
]);
 
// You can choose to render your own GridView separately
echo \kartik\grid\GridView::widget([
    'dataProvider' => $dataProvider,
    'filterModel' => $searchModel,
    'columns' => $gridColumns
]);


?>
```

I'm getting this error:

Invalid Configuration – yii\base\InvalidConfigException

The 'gridview' module MUST be setup in your Yii configuration file and must be an instance of 'kartik\grid\Module'.

I assume my $dataProvider isn't correct somehow?

**Comment by kevinkt** [comment] 2016-01-04 07:39
Also this code below returns the following error as well:

PHP Notice – yii\base\ErrorException

Undefined variable: dataProvider


```
use kartik\export\ExportMenu;

$gridColumns = [
    ['class' => 'yii\grid\SerialColumn'],
    'full_name',
    'email',
    ['class' => 'yii\grid\ActionColumn'],
];

 
// Renders a export dropdown menu
echo ExportMenu::widget([
    'dataProvider' => $dataProvider,
    'columns' => $gridColumns
]);
 
// You can choose to render your own GridView separately
echo \kartik\grid\GridView::widget([
    'dataProvider' => $dataProvider,
    'filterModel' => $searchModel,
    'columns' => $gridColumns
]);

```

**Comment by kevinkt** [comment] 2016-01-04 18:48
Okay so I progressed on this issue. Had to set up the gridview module under config/web.php. Unfortunately, the yii2-export function still isn't working. Clicking on the export button doesn't do anything.

**Comment by kartik-v** [comment] 2016-01-05 02:25
You may need to debug your browser console for any JS errors specific to your app. You can cross check the [docs and demos pages](http://demos.krajee.com/export) for ensuring the right config and check the demos if they work. 

Cannot reproduce this and more config related. So closing this.

You may ask for programming tips and generic help queries in this [new Q&A forum].(http://webtips.krajee.com/questions)

**Closed by kartik-v** 2016-01-05 02:25 UTC

**Comment by kevinkt** [comment] 2016-01-05 18:39
Thanks for the help Kartik!

--
Kevin Tang
